version: '2.1'
services:

  counter1:
    image: randysecrist/dist_counter
    container_name: counter1
    networks:
      vpcbr:
        ipv4_address: 10.5.0.5
    ports:
      - "7777:7777"
    command: ["iex", "--name", "counter1@10.5.0.5", "--cookie", "monster", "-S", "mix"]
    environment:
      - CHALLENGE_ID=1
      - ACTORS=${ACTORS}
    healthcheck:
        test: ["CMD", "curl", "-f", "http://counter1:7777/ping"]
        interval: 2s
        retries: 10

  counter2:
    image: randysecrist/dist_counter
    container_name: counter2
    networks:
      vpcbr:
        ipv4_address: 10.5.0.6
    ports:
      - "8888:7777"
    command: ["iex", "--name", "counter2@10.5.0.6", "--cookie", "monster", "-S", "mix"]
    environment:
      - CHALLENGE_ID=2
      - ACTORS=${ACTORS}
    healthcheck:
        test: ["CMD", "curl", "-f", "http://counter2:7777/ping"]
        interval: 2s
        retries: 10

  counter3:
    image: randysecrist/dist_counter
    container_name: counter3
    networks:
      vpcbr:
        ipv4_address: 10.5.0.7
    ports:
      - "9999:7777"
    command: ["iex", "--name", "counter3@10.5.0.7", "--cookie", "monster", "-S", "mix"]
    environment:
      - CHALLENGE_ID=3
      - ACTORS=${ACTORS}
    healthcheck:
        test: ["CMD", "curl", "-f", "http://counter3:7777/ping"]
        interval: 2s
        retries: 10

networks:
  vpcbr:
    driver: bridge
    ipam:
     config:
       - subnet: 10.5.0.0/16
         gateway: 10.5.0.1
