version: '2.1'
services:

  counter1:
    image: randysecrist/dist_counter:master
    container_name: counter1
    networks:
      vpcbr:
        ipv4_address: 10.5.0.5
    ports:
      - "7777:7777"
    environment:
      - NODE_SNAME=counter1
      - NODE_IP=10.5.0.5
      - NODE_COOKIE=monster
      - CHALLENGE_ID=1
    env_file:
      - docker/dist_counter.env
    healthcheck:
        test: ["CMD", "curl", "-f", "http://counter1:7777/ping"]
        interval: 2s
        retries: 10
    mem_limit: 128m

  counter2:
    image: randysecrist/dist_counter:master
    container_name: counter2
    networks:
      vpcbr:
        ipv4_address: 10.5.0.6
    ports:
      - "8888:7777"
    environment:
      - NODE_SNAME=counter2
      - NODE_IP=10.5.0.6
      - NODE_COOKIE=monster
      - CHALLENGE_ID=2
    env_file:
      - docker/dist_counter.env
    healthcheck:
        test: ["CMD", "curl", "-f", "http://counter2:7777/ping"]
        interval: 2s
        retries: 10
    mem_limit: 128m

  counter3:
    image: randysecrist/dist_counter:master
    container_name: counter3
    networks:
      vpcbr:
        ipv4_address: 10.5.0.7
    ports:
      - "9999:7777"
    environment:
      - NODE_SNAME=counter3
      - NODE_IP=10.5.0.7
      - NODE_COOKIE=monster
      - CHALLENGE_ID=3
    env_file:
      - docker/dist_counter.env
    healthcheck:
        test: ["CMD", "curl", "-f", "http://counter3:7777/ping"]
        interval: 2s
        retries: 10
    mem_limit: 128m

networks:
  vpcbr:
    driver: bridge
    ipam:
     config:
       - subnet: 10.5.0.0/16
         gateway: 10.5.0.1
