version: '2.1'
services:

  counter1:
    image: randysecrist/dist_counter
    container_name: counter1
    ports:
      - "7777:7777"
    command: ["iex", "--name", "counter1@0.0.0.0", "--cookie", "monster", "--erl", "inet_dist_listen_min 6000 inet_dist_listen_max 6999", "-S", "mix"]
    environment:
      - CHALLENGE_ID=1
      - ACTORS=${ACTORS}
    healthcheck:
        test: ["CMD", "curl", "-f", "http://counter1:7777/ping"]
        interval: 2s
        retries: 10

  counter2:
    image: randysecrist/dist_counter
    container_name: counter2
    ports:
      - "8888:7777"
    command: ["iex", "--name", "counter2@0.0.0.0", "--cookie", "monster", "--erl", "inet_dist_listen_min 6000 inet_dist_listen_max 6999", "-S", "mix"]
    environment:
      - CHALLENGE_ID=2
      - ACTORS=${ACTORS}
    healthcheck:
        test: ["CMD", "curl", "-f", "http://counter2:7777/ping"]
        interval: 2s
        retries: 10

  counter3:
    image: randysecrist/dist_counter
    container_name: counter3
    ports:
      - "9999:7777"
    command: ["iex", "--name", "counter3@0.0.0.0", "--cookie", "monster", "--erl", "inet_dist_listen_min 6000 inet_dist_listen_max 6999", "-S", "mix"]
    environment:
      - CHALLENGE_ID=3
      - ACTORS=${ACTORS}
    healthcheck:
        test: ["CMD", "curl", "-f", "http://counter3:7777/ping"]
        interval: 2s
        retries: 10
